### ISSUE TITLE
Ignore words less than n chars

### ISSUE THREAD

**Issue by mebigfatguy** [stuarthendren/jdt.spelling#53]
The ignore single character words is great, but i'd like to be able to say ignore words smaller than n characters, at least 1, 2, 3 chars

**Comment by stuarthendren** [comment]
Hi, I've not used eclipse for quite a while so have not been maintaining this, but if it's useful to I'll put it on my todo list or I'd be happy to accept a PR.

**Comment by mebigfatguy** [comment]
pull request: https://github.com/stuarthendren/jdt.spelling/pull/54
