### ISSUE TITLE
Not able to install the plugin

### ISSUE THREAD

**Issue by mohanaraosv** [stuarthendren/jdt.spelling#55]
Getting the following error while installing this plugin, Please help

![image](https://user-images.githubusercontent.com/1470114/152461368-3e877cbf-06f5-4a66-a32a-ab7ebe7f4349.png)

**Comment by dexter85** [comment]
I have the same problem, the repository is down.

**Comment by stuarthendren** [comment]
Sorry @mohanaraosv I didn't notice this issue - I don't really maintain this repo anymore as I'm not using eclipse much.
However, when @dexter85 commented I saw the notification and have taken a look at the problem. It seems the aws permission system has changed and they defaulted to private. I've reset the files to public so you should be able to use it now.

I hope you find it useful and, although I'm not actively maintaining it, I'm still happy to review issues and accept PRs.
